language: node_js
node_js:
    - "6"
    - "7"
    - "8"
before_script:
    - if [[ $(node -v) =~ ^v4.* ]]; then export __node_harmony=--harmony; fi
    - yarn global add grunt-cli
script:
    - npm run build
deploy:
    skip_cleanup: true
    provider: script
    script: npm run gh-pages
    on:
        branch: production
